- name: Create VPC
  hosts: local
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/zone
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
        - name: Destroy a subnetwork
        gcp_compute_subnetwork:
          name: ansiblenet
          project: "{{ project }}"
          auth_kind: "{{ auth_kind }}"
          service_account_file: "{{ credentials_file }}"
          state: absent
      - name: Destroy a network
        gcp_compute_network:
          name: network-subnetwork
          project: "{{ project }}"
          auth_kind: "{{ auth_kind }}"
          service_account_file: "{{ credentials_file }}"
          state: absent
        register: network