- name: Create VPC
  hosts: local
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/zone
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
      - name: Delete a subnetwork
        gcp_compute_subnetwork:
          name: ansiblenet2
          region: "{{ region }}"
          network: "{{ network }}"
          ip_cidr_range: 10.164.5.48/28
          project: "{{ project }}"
          auth_kind: "{{ auth_kind }}"
          service_account_file: "{{ credentials_file }}"
          state: absent