- name: Create VPC
  hosts: local
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/zone
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
      - name: create a network
        gcp_compute_network:
          name: network-subnetwork
          auto_create_subnetworks: 'true'
          project: "{{ project }}"
          auth_kind: "{{ auth_kind }}"
          service_account_file: "{{ credentials_file }}"
          state: present
        register: network
      - name: create a subnetwork
        gcp_compute_subnetwork:
          name: ansiblenet
          region: "{{ region }}"
          network: "{{ network }}"
          ip_cidr_range: 10.164.4.48/28
          project: "{{ project }}"
          auth_kind: "{{ auth_kind }}"
          service_account_file: "{{ credentials_file }}"
          state: present