- name: Create VPC
  hosts: local
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
      - name: create a network
        gcp_compute_network:
          name: "{{ sharedvpcname }}"
          auto_create_subnetworks: 'false'
          project: "{{ sharedvpcprojectid }}"
          auth_kind: "{{ auth_kind }}"
          service_account_file: "{{ credentials_file }}"
          state: present
        register: network
      - name: create a subnetwork
        gcp_compute_subnetwork:
          name: "{{ subnetname }}"
          region: "{{ region }}"
          network: "{{ network }}"
          ip_cidr_range: "{{ subnetaddress }}"
          project: "{{ project }}"
          auth_kind: "{{ auth_kind }}"
          service_account_file: "{{ credentials_file }}"
          state: present
      - name: Run a script with arguments 
        script: /root/Ansible-Vpc/gcloud/shared_vpc_automaiton.sh {{ credentials_file }} {{ sharedvpcprojectid }} {{ serviceprojectid }} {{ networkuser }} {{ subnetname }} {{ region }}  
        register: output
      - debug: var=output